name: Build and deploy ASP.NET Core app to Azure Web App - HeartozaAPI

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: Backend_Heartoza/Heartoza   # 👈 đúng thư mục solution/project

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore
        run: dotnet restore

      - name: Publish
        run: dotnet publish Heartoza.csproj -c Release -o ${{ github.workspace }}/publish
        # Nếu không chắc tên csproj: dùng "dotnet publish -c Release -o ${{ github.workspace }}/publish"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E48CD3C2E0DC47E19171164D0B86BA34 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E5BD2381B4034F3E964D6B7E000718E6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9801C14818C1479399A55B14EE26252F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: HeartozaAPI
          package: ${{ github.workspace }}/publish
          # slot-name: Production   # có thể bỏ, mặc định là production
