name: Build and deploy ASP.Net Core app to Azure Web App - HeartozaAPI

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

env:
  PROJECT_PATH: Heartoza_Backend/Heartoza/Heartoza.csproj
  PUBLISH_DIR: ${{ github.workspace }}/publish

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" -c Release --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release -o "${{ env.PUBLISH_DIR }}" --no-build

      - name: Show publish output (debug)
        run: |
          dir "${{ env.PUBLISH_DIR }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: ./drop

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AA5E9D3337EB40AF9CEA06B27DC758AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF2EC0AA6CCD41C6A82F0437DEF6DE73 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27720306AAD74CB593CE384EDF3FE0CD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'HeartozaAPI'
          slot-name: 'Production'
          package: ./drop
